# dbt Configuration
# NFL Dead Money Pipeline

name: 'nfl_dead_money'
version: '1.0.0'
config-version: 2
profile: 'nfl_dead_money'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nfl_dead_money:
    # Staging layer - clean and standardize raw data
    staging:
      +materialized: table
      +schema: staging
      tags: ['staging']
      
    # Intermediate layer - business logic and joins
    intermediate:
      +materialized: table
      +schema: intermediate
      tags: ['intermediate']
      
    # Mart layer - analytics-ready fact and dimension tables
    marts:
      +materialized: table
      +schema: marts
      tags: ['mart']

on-run-start: "{{ log('Starting dbt run for NFL dead money data pipeline', info=true) }}"
on-run-end: "{{ log('Completed dbt run', info=true) }}"

# Seeds configuration for Spotrac team cap snapshots
seeds:
  nfl_dead_money:
    spotrac_team_cap:
      +schema: staging
      +quote_columns: false
      +column_types:
        team_name: varchar
        team: varchar
        year: int
        active_cap_millions: numeric
        dead_money_millions: numeric
        salary_cap_millions: numeric
        cap_space_millions: numeric
        dead_cap_pct: numeric

# TODO: Configure additional variables and project-specific settings
vars:
  'start_year': 2015
  'end_year': 2024
  'data_freshness_hours': 24
